/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "BuyMeACoffee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BuyMeACoffee__factory>;
    getContractFactory(
      name: "TakaCommunity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TakaCommunity__factory>;
    getContractFactory(
      name: "TakaInvestment",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TakaInvestment__factory>;
    getContractFactory(
      name: "TakaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TakaToken__factory>;
    getContractFactory(
      name: "TrashCollection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrashCollection__factory>;
    getContractFactory(
      name: "VNDToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VNDToken__factory>;
    getContractFactory(
      name: "YourContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YourContract__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "BuyMeACoffee",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BuyMeACoffee>;
    getContractAt(
      name: "TakaCommunity",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TakaCommunity>;
    getContractAt(
      name: "TakaInvestment",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TakaInvestment>;
    getContractAt(
      name: "TakaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TakaToken>;
    getContractAt(
      name: "TrashCollection",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrashCollection>;
    getContractAt(
      name: "VNDToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VNDToken>;
    getContractAt(
      name: "YourContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YourContract>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "BuyMeACoffee",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BuyMeACoffee>;
    deployContract(
      name: "TakaCommunity",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TakaCommunity>;
    deployContract(
      name: "TakaInvestment",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TakaInvestment>;
    deployContract(
      name: "TakaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TakaToken>;
    deployContract(
      name: "TrashCollection",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrashCollection>;
    deployContract(
      name: "VNDToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VNDToken>;
    deployContract(
      name: "YourContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YourContract>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "BuyMeACoffee",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BuyMeACoffee>;
    deployContract(
      name: "TakaCommunity",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TakaCommunity>;
    deployContract(
      name: "TakaInvestment",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TakaInvestment>;
    deployContract(
      name: "TakaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TakaToken>;
    deployContract(
      name: "TrashCollection",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrashCollection>;
    deployContract(
      name: "VNDToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VNDToken>;
    deployContract(
      name: "YourContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YourContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
