/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Pausable } from "./@openzeppelin/contracts/security/Pausable";
export { Pausable__factory } from "./factories/@openzeppelin/contracts/security/Pausable__factory";
export type { ERC20 } from "./@openzeppelin/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory";
export type { IERC20Metadata } from "./@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { BuyMeACoffee } from "./contracts/BuyMeACoffee";
export { BuyMeACoffee__factory } from "./factories/contracts/BuyMeACoffee__factory";
export type { TakaCommunity } from "./contracts/TakaCommunity";
export { TakaCommunity__factory } from "./factories/contracts/TakaCommunity__factory";
export type { TakaInvestment } from "./contracts/TakaInvestment";
export { TakaInvestment__factory } from "./factories/contracts/TakaInvestment__factory";
export type { TakaToken } from "./contracts/TakaToken";
export { TakaToken__factory } from "./factories/contracts/TakaToken__factory";
export type { TrashCollection } from "./contracts/TrashCollection";
export { TrashCollection__factory } from "./factories/contracts/TrashCollection__factory";
export type { VNDToken } from "./contracts/VNDToken";
export { VNDToken__factory } from "./factories/contracts/VNDToken__factory";
export type { YourContract } from "./contracts/YourContract";
export { YourContract__factory } from "./factories/contracts/YourContract__factory";
