/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BuyMeACoffee } from "./BuyMeACoffee";
export type { VNDToken } from "./VNDToken";
export type { YourContract } from "./YourContract";
