/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BuyMeACoffee } from "./BuyMeACoffee";
export type { TakaCommunity } from "./TakaCommunity";
export type { TakaInvestment } from "./TakaInvestment";
export type { TakaToken } from "./TakaToken";
export type { TrashCollection } from "./TrashCollection";
export type { VNDToken } from "./VNDToken";
export type { YourContract } from "./YourContract";
